### ISSUE TITLE
Using traversals in L.pick

### ISSUE THREAD

**Issue by elysion** [calmm-js/partial.lenses#109]
I am trying to map a data structure received from one API to a format that would be suitable for another API. L.pick works well when using lenses with single focus but in my case, I would also need to be able to pick properties from list items. Consider the following example:

```JavaScript
const data = {
  a: [
    {b: 1, c: 1},
    {b: 2, c: 2},
    {b: 3, c: 3}
  ],
  d: {e: 'a'}
}

L.get(
  L.pick({
    stuff: L.pick({
      b: ['a', L.elems, 'b'] // L.elems does not work here
    }),
    otherStuff: ['d', 'e']
  }), data)

const desiredResult = {
  stuff: [
    {b: 1},
    {b: 2},
    {b: 3},
  ],
  otherStuff: 'a'
}
```

The example will not run, because L.get throws the following error:
```partial.lenses: `elems` requires an applicative. Given: { map: [Function: sndU] }```

I do realize that L.pick expects lenses to be passed in and thus this use of the API is invalid. Anyhow being able to transform data structures in this manner would be very useful imho.

**Comment by polytypic** [comment]
In case you only want a unidirectional operation, you can freely compose optics with functions.  So, you could say ([playground](https://calmm-js.github.io/partial.lenses/playground.html#MYewdgzgLgBAJgQygmBeGBvAUAgXDAbSwwCN8BGAGhmAoF9LiyYAma21hp-AZnd7pYAuozj4MAU3wByBNMGCsAGQB0AcwlQAFMpUAHAJbAA1luzQArgDMr+VaAA2DicG0FZ06qonOAthC99ACcQPQgtaRJpAEohaMYQKAALCSCAZShrW0JpOE8YaQlpISw6eKxEZGigA)):

```js
L.get(
  L.pick({
    stuff: L.collect(['a', L.elems, L.props('b')]),
    otherStuff: ['d', 'e']
  }),
  data)
```

Above `L.collect(...)` results in an ordinary function that will be used as a read-only optic.

[The company example](https://stackblitz.com/edit/calmm-company) uses the above technique in one half of the `joinView` isomorphism constructor.

BTW, the [Gitter channel](https://gitter.im/calmm-js/chat) is also good for questions like this.

**Comment by elysion** [comment]
Oh, did not realize I could use functions like that or use Gitter. Using functions in the lenses do solve the problems I currently have as I do not need to use the lense in the other direction. Being able to use the traversals with pick in both directions sounds like something that could be useful in other cases.

**Comment by polytypic** [comment]
I just realized that there is likely a better way to handle this case.  What you are actually looking for here is a kind of adapter between two forms of the same data.  We can express that using isomorphisms.  Here is a [playground](https://calmm-js.github.io/partial.lenses/playground.html#MYewdgzgLgBAhgJwXAnjAvDApgGywWwwD4YAZAOgEsIQAKC-EAE0oDMV7zcCIAaM8gHMsUWt3wBKCbwBQDZmw4VxfAcKgBJMADcsCCFjF5JUmTNCRYTOFDgYYAbxlwAXDADaMhwCM3ARn5gfwBfWR83ACZAyNCvXxgAZmjE4JkAXVkmNwcsNwByODzU1PNwaHhrAAcoPXsKSspgAGtaJ2gAV1ZWN3rGlqd49wK8-kRkJXJKhBBKiFo87zypNJlg6RkQKAALPQBlKE7ujzymEZg8rDyVtbMLGjxyHBBBWjURWjgqmoR+a1sJGASUqQEAPJ4vN6aHR6AwfL56fgUdRwuDVBEwP5wKSAoA) that does just that.  In this case the adapter is lossy, but notice that the adapter works in both directions.  I'll add the `array` iso constructor to the library when I have a moment.
