### ISSUE TITLE
Improve export style

### ISSUE THREAD

**Issue by ivan-kleshnin** [calmm-js/partial.lenses#14]
Newer Babel 6 removes hacks for `require` which were never actually ES6 compatible.
Then:

```js
let L = require("partial.lenses")
console.log(L.lens) // nope :(
```

```js
import {lens} from "partial.lenses"; // nope :(
```

only those two is working:

```js
let L = require("partial.lenses").default // :(
console.log(L.lens) // yep
```

```js
import L from "partial.lenses"; 
let {lens} = L // yep
```

The reason why it breaks is that in ES5 and classic Node `require` you export **values** while
in ES6 you export **bindings**. This is to make **tree shaking** possible.

So if the library is a collection of helpers (like in your case) 
you shouldn't `export default` from it.

In other words we were told to avoid

```js 
import * as foo from ...
```

in favor of `export default` + `import foo from ...`
but *the first* style is actually the right and the **only working** way 
to import from multi-export library in ES6 & Babel6. 

---

[**See this issue**](http://stackoverflow.com/questions/33505992/babel-6-changes-how-it-exports-default)

---

As enforcing users to add `.default` is not correct you need to update your exports
to be like

```
export foo
export bar
```

rather than

```
L.foo = foo
L.bar = bar
export default L
```

P.S.
I saw you export `lift` separately but I've got no further time for checkings.
You decide what do to with that. I avoid ES6 style imports because they are Stage-0
and I want to be able to use vanilla node for isomorphic apps.

**Comment by polytypic** [comment]
Thanks!  Yes, I'm aware of this.  We are using

```js
import L from "partial.lenses"; 
```

style imports and it is convenient that we then get access to the whole set of combinators and a concise notation for composition `L(...)`.  The disadvantage is that dead-code elimination becomes more difficult.

Perhaps there is a reasonable compromise between convenience and compatibility.  How about something like

```js
import Ls, * as L from "partial.lenses"
```

where `Ls` is same as `L.compose`.

**Comment by ivan-kleshnin** [comment]
I think there is no way to achieve all that unfortunately. 

```js
import Ls, * as L from "partial.lenses"
```

is a correct ES6, tree-shaking compatible way. 

Which can't be reproduced in CommonJS where you can only 

```js
let Ls, {view} = require("partial.lenses")
```

hitting the wall with the `set` keyword.

Let's suppose being future-proof is more imporant here (delaying breaking changes is a bad idea).
So your proposition seems the best option available to me as well.

**Comment by polytypic** [comment]
IMO, `set` is the wrong term to use anyway.  It is copied from Ramda: [`set`](http://ramdajs.com/0.19.0/docs/#set).  Perhaps it should be renamed to something else such as `update`. Coincidentally, Ramda's [`update`](http://ramdajs.com/0.19.0/docs/#update) would then provide a subset of the functionality.  IOW, currently `L.set(i, x, xs)` does the same thing as `R.update(i, x, xs)` assuming that `0 <= i && i < xs.length`.

**Comment by ivan-kleshnin** [comment]
Yep, I saw gripes about `set` but they've left it for now.
Comparison with `update` seems legit. I don't have enough experience to judge that though.

**Comment by polytypic** [comment]
FYI, I think this should be done.  However, I plan to finish the first version of Calm^2 intro manual first, which will likely take at least a day or two or more.  Anyone is welcome to make a pull request for the change before that. :)  (Just drop a note here.  Aside from the proposed changes (implementation, doc and test changes), add a short Changelog.md that notes why the change was made (couple of sentences) and how to upgrade (perhaps as a couple of code sample diffs that GitHub can display nicely).)
