### ISSUE TITLE
Add `get` as alias for `view`

### ISSUE THREAD

**Issue by raimohanska** [calmm-js/partial.lenses#16]
I wasted a while wondering where the `get` function has disappeared. For me, `get` would seem like a nice pair for `set` :)

Great work btw!

**Comment by raimohanska** [comment]
Also, I'm still looking for `modify(lens, f)`

**Comment by polytypic** [comment]
[`over`](https://github.com/calmm-js/partial.lenses#loverl-x2x-s) is the `modify` you are looking for.

I've copied the names of operations from Ramda.  I agree that the names are not "optimal", but it is more difficult to decide the best choice of names would be.  For instance, I don't particularly like the name `set`.  I would prefer `update` as in "functional record update".  Ramda also uses the name `update` for a functional update operation on arrays whose semantics coincides with partial lens `set`.

current | proposed
:------:|:-----:
`view` | `get`
`set` | `set`
`over` | `modify`

Perhaps it would not hurt to have the proposed aliases.  Opinions welcome!

**Comment by polytypic** [comment]
2.2.0 introduced `get` and `modify` as synonyms for (deprecated) `view` and `over`
3.0.0 removed `view` and `over`.
