### ISSUE TITLE
How to read source code?

### ISSUE THREAD

**Issue by jituanlin** [calmm-js/partial.lenses#160]
Yes, this project is cool, but when I read it's source code, I am so confuse. It's code style is so different,
even I have functional programming language  experience like Haskell, Clojure, Scala. What knowledge should I have in order to understand this code

**Comment by polytypic** [comment]
Yes, the implementation has lots of low level optimizations, so it is fairly complex in places.  I recently wrote a short document that describes a simplified implementation: [Partial Lenses Implementation](https://calmm-js.github.io/partial.lenses/implementation.html).  The wiki also contains a page on traversals: [Traversals in depth](https://github.com/calmm-js/partial.lenses/wiki/Traversals-in-depth).  Other than that, I'd recommend asking more specific questions on the implementation.  You can ask here or you can join the [Gitter channel](https://gitter.im/calmm-js/chat) and ask there.

**Comment by jituanlin** [comment]
@polytypic  Thanks!
