### ISSUE TITLE
Index isomorphism

### ISSUE THREAD

**Issue by shtanton** [calmm-js/partial.lenses#180]
Not sure if this has been suggested before or even if it is already implemented (neither as far as I can tell), but I think a useful function could take an array as a parameter, and return an isomorphism that goes between a value and its index in that array.

Obviously there would need to be some logic dictating what to do if the value isn't in the array or if the index is invalid.

If this is a good idea I would be happy to have a go at creating a PR for it

Thanks

**Comment by polytypic** [comment]
Hmm... Do you mean something like [this](https://calmm-js.github.io/partial.lenses/playground.html#MYewdgzgLgBAlmAJgUwB4HkBmMC8MBuAhgDYCuyEuAfDADIB0cEIAFAFCrUwDeboksOLgIlyEepgSIAkkjQsASvWQBHUiQgtUASm1sATsiil9YeDAA8MAAwwA-DFJzJYZIhgAueGwC+AGjYhHBoiMgoAbTgAXTY9NmIQAHMWAHIAIwB3RBS-OnpEoxYpNCwWcJTCHJh0lKjtXJrtGD0E5JTMLKqGAqhZfGR9CGQiuQxMMoqqmrrcgEYm7SA)?

**Comment by shtanton** [comment]
Yep, pretty much exactly that, that's almost identical to what I've been using, but I figured it seemed useful enough that it could be included

**Comment by shtanton** [comment]
Thanks for the detailed response, I hadn't thought of composing `find` and `is` to produce the same result as the contains lens, because it can be so easily produced from existing lenses, it's probably not worth adding it as its own lens.

My use case for the index isomorphism was to show a list of items, and have elsewhere a form that involves selecting using the index of the list item.  It doesn't really require the use of lenses but I thought it would be more fun this way.  I expect that most of the time, it is better to store the index as state instead of the item itself as `indexOf` might be quite slow for large arrays, which I think would limit its usefulness.
