### ISSUE TITLE
I'd like to L.traverse an object

### ISSUE THREAD

**Issue by mweichert** [calmm-js/partial.lenses#193]
Any suggestions of how to go about this?

E.g.

```js
const structure = {
    foo: 'bar',
    foobar: {
        foo: 2,
        bar: 4
    }
}

const optic = ['foobar', L.values]

L.traverse(Future, later, optic, structure).fork(console.log, console.log)
```

**Comment by polytypic** [comment]
I assume `Future` comes from the `fluture` package.  Partial Lenses uses static land, so what one needs to do is to construct a static land compatible applicative.  For example:

```js
const Future = require("fluture")
const L = require("partial.lenses")

const structure = {
  foo: 'bar',
  foobar: {
    foo: 2,
    bar: 4
  }
}

const optic = ['foobar', L.values]

const fromFantasyApplicative = Type => ({
  of: Type.of,
  map: (f, x) => x.map(f),
  ap: (f, x) => f.ap(x)
})

L.traverse(
  fromFantasyApplicative(Future),
  x => Future.of(x + 1),
  optic,
  structure
).fork(
  err => console.log('Error', err),
  res => console.log('Result', res)
)
```

Here is [the above code in RunKit](https://runkit.com/embed/t7c3z62tpfpk).

BTW, whether you are just trying out or using the library, I recommend joining the [Gitter channel](https://gitter.im/calmm-js/chat).

**Comment by polytypic** [comment]
Working on #194

**Comment by polytypic** [comment]
Oh... Of course, given that `Future` of `fluture` is already static land compatible, you don't need to convert to static land.  So, the following also just works:

```js
const Future = require("fluture")
const L = require("partial.lenses")

const structure = {
  foo: 'bar',
  foobar: {
    foo: 2,
    bar: 4
  }
}

const optic = ['foobar', L.values]

L.traverse(
  Future,
  x => Future.of(x + 1),
  optic,
  structure
).fork(
  err => console.log('Error', err),
  res => console.log('Result', res)
)
```

Here is [the above code in RunKit](https://runkit.com/embed/5v28dlbohaai).

**Comment by mweichert** [comment]
Thanks @polytypic for the quick response and great assistance. I was using data.task actually but your examples gave me exactly what I needed to better understand traversals, traverse, and static land.
