### ISSUE TITLE
Nested matches for L.satisfying

### ISSUE THREAD

**Issue by abraham-chan** [calmm-js/partial.lenses#214]
https://calmm-js.github.io/partial.lenses/playground.html#MYewdgzgLgBAJgQygmBeGBtAUAbxggLhigCcBXAUwBoZgALASwBs4SKwiMcG4iBGGoWLkKAXwC6MUVVz4iAMwRMI1WoxZsOmbrxgAmQUVKUJUmeKxYAMgDpQTJhWBQAFLYhIGEeQE8GYAHMXACUbAAcSEDCXACIEGIBKBJpEZASAbiA

```
const data = [
  { a: true, children: [{id: 1, a: true}] },
  { a: false, children: [{id: 2, a: true}] },
]

L.collect(L.satisfying(R.prop("a")), data);
```
Results in:
```
Array [
  Object {
    "a": true,
    "children": Array [
      Object {
        "a": true,
        "id": 1,
      },
    ],
  },
  Object {
    "a": true,
    "id": 2,
  },
]
```

I was also expecting to see 
```
  Object {
    "a": true,
    "id": 1,
  }
```

Is this the intended behaviour?

**Comment by polytypic** [comment]
Yes, that behaviour is intended.  One reason is that a fundamental property of applicative traversals is that [traversals operate over non-overlapping focuses](https://github.com/calmm-js/partial.lenses/#traversals).  Also, it is possible to use e.g. [`L.lazy`](https://github.com/calmm-js/partial.lenses#L-lazy) to create an optic with some recursive behaviour from an optic without such recursive behaviour, but it is not possible to take out recursive behaviour from an optic (so non-recursive building blocks are more versatile).

One way to use traversals for something like this is to make the focuses non-overlapping by dividing objects with children into two [disjoint](https://github.com/calmm-js/partial.lenses#L-disjoint) subsets: one with only the children and another with everything except the children.  Here is [an example](https://calmm-js.github.io/partial.lenses/playground.html#MYewdgzgLgBAJgQygmBeGBtAUAbxggLhigCcBXAUwBoZgALASwBs4SKwiMcG4iBGGoWLkKAXwC6MUVVz4iAMwRMI1WoxZsOmbrxgAmQUVKUJUmeKxYAMgDpQTJhWBQAFNZtMEALwCebtsBoAHyY7hBIDBDyPgxgAOYuAEo2AA4kICkuAEQIWQCUeTK2DPIAosoUbsl0CBAuAOT0zKzs9YVYGLZwkQBWILGuANbBMMOo4zCN6i1g9TAA-KMwRPUgUHQUJBBtNAHiMhgWeVhHMojIWHlAA).  By dividing the objects like that into disjoint subsets it is still possible to update the objects in a single pass.

It is also possible to use the monadic [`L.seq`](https://github.com/calmm-js/partial.lenses/#L-seq) combinator to operate on a single focus multiple times and collect the results with a suitable monad, but then you lose the nice properties of applicative traversals.  Such a monadic collect is not provided out of the box, but there is [test code that does it](https://github.com/calmm-js/partial.lenses/blob/master/test/tests.js#L69-L97) and [here is an example](https://calmm-js.github.io/partial.lenses/playground.html#MYewdgzgLgBAsuAhgExgXhgCgN4gGYA0MwAFogJZgC+AlOgHxbYBQ+BzpFY7iADgFxYAHgCYAngGUiQiXTSNOlTKLENiZJULX5l45TRrTZ08ceYBbPoN1ijchRrDLteG-sMwZNZrWYdw0PB8AMLgwIhQAPJ46PDgIOSo8nFgKDiseIJayQDaQkQIYAnIAHQApua8UGKYNAC67Ipg1ipwRHlEEABOdfYwLKCQsDm2MBAANnWxrfrMXWVQAK5dYDAjBfGJJYPhUJgTnV31Pj7e-kMwoePjZcCwGCwVVWLWfZEARgBWt1AlePNlABeZUwOV6jTCEWs4wgRC6EDeXx+fwBwNBJQx8KIGJKMN6J3OgSuNzucFicBCkKirmJPzOg0CoGuPzJGAAkttll0asxMCBOvZmAAZEpQEAAMUWYDu5HAfJomA+3zuKLKQJBCKIUuQZTwlDKyCItNJ0jUHTWQjqvRyAEY6sx6QFYMgIohYjlmNgYIhBFAuosykRSORxsh5s01thEoIbUQfTA-QGqFMqOwvfG8IgYYH1CGw2UIzko8hBCI477-WVkzBU8x7f5maTMMLcYhATz5sAzS2IBFyBA8GJKABzTAAJRKvC6IF4mAARIg5wZ2CKIGUAI6ghprADkwdD4Z3cNu+PthmYLqgiAdQA).

**Comment by abraham-chan** [comment]
Thanks for the constructive response! Really appreciate the effort you put into this project :+1:
