### ISSUE TITLE
browser compatible?

### ISSUE THREAD

**Issue by tycho01** [calmm-js/partial.lenses#63]
Currently it looks like the code uses `process.env.NODE_ENV`, implying the project is only for use with Node. I haven't tried it by browser yet, but I wonder if there'd be a way to ensure it works both ways.

**Comment by polytypic** [comment]
Yes, there are couple of ways to use this lib in browsers. (Actually I've mostly used lenses in client side apps.) One is to use e.g. browserify with envify to build a bundle for browsers. (See `package.json`.) Or you can use the prebuilt files in the dist directory. They can be installed via bower also. They include a module loader prefix. You will also need the intestines lib, which you may need to include explicitly depending on which tooling you use. Currently this library uses `Object.assign` which may not be present in all relevant browsers.

**Comment by tycho01** [comment]
Ah, the precompile step looks interesting, I hadn't noticed that one yet.

I'll concede I'm better versed with webpack than with browserify though, so that does still leave me with a few questions w.r.t. how options like envify might cover this.

It looks like Sanctuary was using a slightly more [configurable](https://github.com/sanctuary-js/sanctuary/blob/master/index.js#L424) approach here, allowing users to just specify whether to perform the run-time type checks whether using Node or whatever.

I'd wonder, might you be open to the idea of a more agnostic approach like that here as well?

**Comment by polytypic** [comment]
I haven't used Webpack, but it should be possible to configure it to eliminate the `process.env.NODE_ENV` usages. The use of `process.env.NODE_ENV` is common practice.   Googling a bit here is [a post that discusses dealing with `NODE_ENV` with Webpack](http://jonnyreeves.co.uk/2016/simple-webpack-prod-and-dev-config/).

**Comment by tycho01** [comment]
Interesting stuff, thanks for that! Let's consider this addressed. :)
