### ISSUE TITLE
lensing objects: L.merge?

### ISSUE THREAD

**Issue by tycho01** [calmm-js/partial.lenses#73]
In the spirit of (batch) [`upsert`](https://wiki.postgresql.org/wiki/UPSERT), I wonder if, not unlike `L.append` for updating existing arrays, writing to existing objects might have use for something like `L.merge` (just a lens equivalent of `R.merge`).
There might be more, but this just stood out to me as a more likely addition to flesh things out.

**Comment by polytypic** [comment]
(Replying with a mobile.) Hmm... Could you give an example of what you have in mind?

**Comment by tycho01** [comment]
```js
L.merge(['foo'], { b: 2, c: 3 }, { foo: { a: 1, b: 0 } }); // { foo: { a: 1, b: 2, c: 3 } }
```
That is to say, I'm imagining an existing object structure to get updated based on the values in the provided object.

**Comment by polytypic** [comment]
Hmm... How about this:

```js
L.modify('foo', R.merge(R.__, { b: 2, c: 3 }), { foo: { a: 1, b: 0 } })
// { foo: { a: 1, b: 2, c: 3 } }
```

**Comment by tycho01** [comment]
Well, that works. Thanks! :)

**Comment by polytypic** [comment]
With PR #104 one could say:

```js
L.assign('foo', { b: 2, c: 3 }, { foo: { a: 1, b: 0 } })
// { foo: { a: 1, b: 2, c: 3 } }
```

**Comment by tycho01** [comment]
Thanks for the follow-up! That's awesome, looks like object manipulation just got more pleasant. :)
