### ISSUE TITLE
Document object template of lenses 

### ISSUE THREAD

**Issue by ivan-kleshnin** [calmm-js/partial.lenses#96]
Docs mention "object template of lenses" few times but it's never documented.
By trial and error I figured out that currently it supports plain values and arrays but not nested values.

For example, I want to pick `meta.file` property chain from a given object. 

```js
let obj = {meta: {file: "./foo.txt", base: "foo", ext: "txt"}}
L.get(L.pick({file: ["meta", "file"]}), obj}) // {file: "./foo.txt"}
```

now I want to grab both `file` and `ext` but not `base` keeping the original nesting:

```js
let obj = {meta: {file: "./foo.txt", base: "foo", ext: "txt"}}
L.get(L.pick({???}), obj}) // {meta: {file: "./foo.txt", ext: "txt"}}
```

I guess it's not possible with `L.pick` (because output is a product hence a plain collection), but not sure because it's unclear what "template of lenses" is.

P.S.

I'm aware of a solution:

```js
R.pipe(
  L.set(["meta", "file"], L.get(["meta", "file"], obj)),
  L.set(["meta", "ext"], L.get(["meta", "ext"], obj))
)({})
```

I just wondered maybe I missed a shorter option.

**Comment by polytypic** [comment]
Yes, the documentation could be clarified here.  The template for `L.pick` cannot directly be a nested object.  However, you can do nested things by nesting optics.  For example ([see in playground](https://calmm-js.github.io/partial.lenses/playground.html#DYUwLgBA9gRgVhAvBA3gW3AQwFyoGYCWouARAHQD0eUUZYAHmCQDQQyYDOIp1ULEIRqQZMAvqIBQAGTIBzcAAoZABwIBjANYL0WXAG0SGMJn4qATlGUcFJQqH4lBTAJQBdUc9aw4zoA)):

```js
let obj = {meta: {file: "./foo.txt", base: "foo", ext: "txt"}}
L.get(L.pick({meta: ["meta", L.props("file", "ext")]}), obj)
```

Don't have time to think this through right now, but there might be ways to allow for some form of nest nested version of `L.props` to make this kind of usage nicer.

**Comment by polytypic** [comment]
Here is a kind of nested cross of `L.pick` and `L.props` ([try in playground](https://calmm-js.github.io/partial.lenses/playground.html#DYUwLgBA9gRgVhAvBA3gW3AQwFyoGYCWouARAHQD0eUUZYAHmCQDQQyYDOIp1ULEIRqQZMAvqIBQEgMZQAdh0hyQikABMkESIgB8EABQBJMgQ4B5eCGlh9YAJQSA-BAAyZAA4FpAa31u0UGoEeACefmQAbpjAAK4qrPoRrN52SHoA2t6syqpqiXYAuqz2Drj2Um4A5uD6OWDq+uhYuCiExBDpRQJCHQXidqywcHZAA)):

```js
let obj = {meta: {file: "./foo.txt", base: "foo", ext: "txt"}}

const nested = t => (I.isObject(t)
                     ? L.pick(L.modify(L.values, (v, k) => [k, nested(v)], t))
                     : t)

L.get(nested({meta: {file: [], ext: []}}), obj)
```

You can give it an arbitrary nested template of (plain) objects whose leaf props must be lenses.

Does this seem like what you'd want and what would be a good name for this?  `L.pickNested`? `L.pickIn`?

**Comment by ivan-kleshnin** [comment]
Wow, recursive lensing. 

I'm getting 

> Error: partial.lenses: `pick` expects a plain Object template.

with the last Partial.Lenses version available.

**Comment by polytypic** [comment]
Hmm... Note that the `isObject` predicate from the `infestines` library basically tests that that constructor of the given value is `Object`.  IOW, it doesn't just test that the given value inherits from Object.

**Comment by polytypic** [comment]
BTW, thanks for opening this issue!  I have to think about generalizing `L.branch` and `L.pick` (to accept nested templates) and possibly adding the new `L.pickIn` (aka `nested` above).

**Comment by ivan-kleshnin** [comment]
Hi, Vesa. Sorry for not participating – mad months at work :(
`pickIn` looks like a reasonable solution.

**Comment by polytypic** [comment]
No problem.  I was also just on a tightly scheduled project and finally got some time & energy to finish the initial `pickIn` implementation.  Thanks for opening the issue!
